### PR TITLE
ENH: added new icon button which enables displaying all module specif…

### PR DESCRIPTION
**Pull request by che85**
…ic settings in a popup

- new class SettingsMessageBox that retrieves all settings from qt.QSettings that belong to moduleName

image

### CODE REVIEW

**Comment by che85** [comment]
WIP

**Comment by che85** [comment]
Now looks like 
image

**Comment by fedorov** [comment]
Is there a mechanism to add some explanations to the individual parameters, and show them in tooltips? For example, I am guessing "COVER_PROSTATE" corresponds to the text expected to be found in the SeriesDescription of the cover prostate series, but it may not be obvious to the user.

**Comment by che85** [comment]
This widget only shows settings retrieved from qt.QSettings()

I am not sure, if we can add such functionality

**Comment by fedorov** [comment]
We should add this to the documentation!

**Pull request merged**
