### PR TITLE
ENH: code of SlicerProstateUtils moved to SlicerDevelopmentToolbox

### PR DESCRIPTION
**Pull request by che85**

### CODE REVIEW

**Comment by jamesobutler** [comment]
SlicerProstateTests code is causing a [failing test](http://slicer.cdash.org/testDetails.php?test=9566227&build=1612522) with SlicerPreview. @che85 or @fedorov, should this PR go ahead and be merged?

**Comment by fedorov** [comment]
@che85 I am not sure how it happened that this PR fell through the cracks! Can you confirm it is safe to merge this?

**Comment by jamesobutler** [comment]
It does appear that SlicerProstateUtils was moved to SlicerDevelopmentToolbox https://github.com/QIICR/SlicerDevelopmentToolbox

**Comment by fedorov** [comment]
I don't have time to carefully check this, but since it does look benign, and I don't think this extension is in the critical path, I am going to take the risk and merge this.

**Pull request merged**
